### ISSUE TITLE
`cabal sdist` fails

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/asl-translator#38]
If I check out a fresh copy of `asl-translator` and run `cabal sdist`, it fails with:

```
$ cabal sdist
cabal: sdist of asl-translator-0.1.0.0: filepath wildcard './output/*.what4'
does not match any files.
```

This prevents `asl-translator` from being usable as a [`source-repository-package`](https://cabal.readthedocs.io/en/3.6/cabal-package.html#source-repositories), which uses `cabal sdist` under the hood.

**Comment by RyanGlScott** [comment]
As far as I can tell, the contents of `output` are generated when running the test suite. Is there any reason why the contents of `output`s need to be included in binary distributions? If not, we can just delete [this line](https://github.com/GaloisInc/asl-translator/blob/6b9bcb4d0a1d64910438c2faff37fd1905dd9591/asl-translator.cabal#L18) from the `.cabal` file to fix this issue.

**Comment by travitch** [comment]
I think the contents of `output` are intended to be generated by the `asl-translator-exec` binary. It might be the case that we don't want the `output` files at all. What we really care about are the `archived` files, which are checked in.
