### ISSUE TITLE
Use new what4 printer/parser

### ISSUE THREAD

**Issue by danmatichuk** [GaloisInc/asl-translator#7]
The current serialization/deserialization code is based on the `what4-serialize` branch in the crucible repository. This has been generalized in ongoing work by @pnwamk in https://github.com/pnwamk/crucible which the translator should be ported over to use once this feature is ready.

**Comment by pnwamk** [comment]
Just as an note: I'm currently hooking `semmc` up to use the more generic what4 printer/parser here: https://github.com/pnwamk/semmc/tree/WIP/feature/what4-serialize-progress

When that's done will be a natural point to pause and think about next steps I think (e.g., maybe then look at having `asl-translator` directly use that code/API as well?)

**Comment by danmatichuk** [comment]
Yeah, once we have a working example in semmc then it probably makes sense to do the port. There will be a little bit of nontrivial code that needs to get lifted out of `what4-serialize` since its doing a bunch of work internally to serialize/deserialize an entire function environment, but otherwise it shouldn't be too difficult.
